[build]
  functions = "functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "netlify-lambda"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Access-Control-Allow-Origin = "*"