/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestnetRouteImport } from './routes/testnet'
import { Route as LimboChatbotRouteImport } from './routes/limbo-chatbot'
import { Route as IndexRouteImport } from './routes/index'

const TestnetRoute = TestnetRouteImport.update({
  id: '/testnet',
  path: '/testnet',
  getParentRoute: () => rootRouteImport,
} as any)
const LimboChatbotRoute = LimboChatbotRouteImport.update({
  id: '/limbo-chatbot',
  path: '/limbo-chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/limbo-chatbot': typeof LimboChatbotRoute
  '/testnet': typeof TestnetRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/limbo-chatbot': typeof LimboChatbotRoute
  '/testnet': typeof TestnetRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/limbo-chatbot': typeof LimboChatbotRoute
  '/testnet': typeof TestnetRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/limbo-chatbot' | '/testnet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/limbo-chatbot' | '/testnet'
  id: '__root__' | '/' | '/limbo-chatbot' | '/testnet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LimboChatbotRoute: typeof LimboChatbotRoute
  TestnetRoute: typeof TestnetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testnet': {
      id: '/testnet'
      path: '/testnet'
      fullPath: '/testnet'
      preLoaderRoute: typeof TestnetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/limbo-chatbot': {
      id: '/limbo-chatbot'
      path: '/limbo-chatbot'
      fullPath: '/limbo-chatbot'
      preLoaderRoute: typeof LimboChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LimboChatbotRoute: LimboChatbotRoute,
  TestnetRoute: TestnetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
